[package]
name = "dm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
clap_complete = "4.3.0"
dirs = "4.0.0"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
